AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
    - db/**/*
    - config/**/*

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# For Windows setting.
Style/EndOfLine:
  Enabled: false

Metrics/LineLength:
  Enabled: false